#+html:<h1 align="center">GitHub README.org Hacks</h1>
#+html: <p align="center"><a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-Document-%2377aa99?style=flat-square&logo=org&logoColor=white"> </a><a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Made_with-Emacs-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a></p>

#+html:<div align="center">
Sharing the undocumented things you can do with GitHub, org-mode, and HTML to make a better README.
#+HTML:</div>

#+begin_example :exports none
SECTIONS TO DO NEXT
Hiding Information
- Can be done using:
- :exports none on example or source blocks.
- I keep a private TODO list for this very repository here that you can't see!

Math Support
- Needs fleshed out...
- GitHub
- HTML
- Org
- Latex
  - GitHub now supports LaTeX syntax

NoWeb
- Needs fleshed out...

Quoting
- Centering block quote text
  - #+HTML:<div align="center"><blockquote>centered block quote</blockquote></div>
- Figure out other quoting possibilities.

Org Commands in Code Blocks
- Prepend the commands with , and then they'll magically work! Make this more explicit or give it's own section.

Making Custom SVGs
- Needs fleshed out..

HTML
- <warning>
- <kbd>
- Image alignment,
  - Href images can be aligned to center and left and right
  - Can be used to have text on left and images on the right

Needs research
- Captions
- Notes

Implement things from here but for org:
https://gist.github.com/ChrisTollefson/a3af6d902a74a0afd1c2d79aadc9bb3f
#+end_example

** Why?
The README, is your primary method to portray information about a repository to the reader. GitHub supports using =org-mode= to create a README, but it's implementation using =org-ruby= neither works as claimed nor is complete.

That's where these hacks come in, primarily using HTML, to get around these limitations, as well as to show some additional possibilities and preferences.

And, I haven't found anyone talking about these techniques, so I thought I would share them. Please consider submitting yours.
** Document Structure
This document covers methods to use org-mode and HTML together. The headings are sorted by the goal we want to achieve, not by the method used to achieve it.

** Table of Contents
- [[#background][Background]]
- [[#html-in-org-documents][HTML in Org Documents]]
- [[#centering--text-alignment][Centering / Text Alignment]]
- [[#underlining-1][Underlining]]
- [[#folding-1][Folding]]
- [[#code][Code]]
  - [[#inline-1][Inline]]
  - [[#block-1][Block]]
- [[#tables][Tables]]
- [[#shields][Shields]]
- [[#emojis][Emojis]]

** Background
GitHub uses [[https://github.com/wallyqs/org-ruby][org-ruby]] to parse and export an org document as HTML, then it is sanitized using their [[https://github.com/gjtorikian/html-pipeline/blob/main/lib/html/pipeline/sanitization_filter.rb][HTML-pipeline]].

These documents allow us to understand what you can and can't do using org-mode and HTML on GitHub, but that work is summarized for you here.
*** org-ruby
Through this, org-mode syntax is translated directly into HTML. The rules for translation are modifiable. See org-ruby for the default translation list.

The problem with this, is that the translations used by GitHub/org-ruby are incomplete. This can be fixed by including a YAML file, but we don't need another file in our repository just for formatting a README.

The point is, that most things you can do with org-mode are supported, but some things are not. For example, headings are translated directly to HTML heading tags (<h1>,<h2>,etc.), tables are translated to table tags (<table>), etc.

#+html:<p><ins>However, the following do not work correctly and must be fixed using HTML:</ins></p>
**** Centering
#+html:<p>Org-mode's <code>#+begin_center</code> and <code>#+end_center</code> syntax are translated to <code>&lt;div&gt;</code> but it's missing the <code>align="center"</code> attribute.

**** Underlining
Org-mode's underline syntax =_text_= is translated to ~<span style=\"text-decoration:underline;\>~ which is incorrect and not honored by GitHub.

**** Folding
In general this is missing from org-mode, a feature that markdown has and "we" don't.

** HTML in Org Documents
#+html:<p align="center">Welcome our Lord and Savior, HTML!</p>

Although this is our primary method of overcoming the limitations of org-ruby and GitHub, it should be noted that HTML offers us so much more than just fixing org-ruby's shortcomings.

Org-mode supports the use of two syntaxes for writing HTML in a document.
*** Inline
Useful for one-liners.

Syntax:
#+begin_src
#+html:
#+end_src

Example:
#+BEGIN_SRC
#+HTML:<p>Some HTML</p>
#+END_SRC

*** Block
Useful for complex or multi-line HTML.

Syntax:
#+html:<pre>#+begin_html<br>#+end_html</pre>

Example:
#+html:<pre>#+begin_html<br>&lt;div&gt;<br>&lt;p&gt;Some longer HTML!&lt;/p&gt;<br>&lt;/div&gt;<br>#+end_html</pre>

*** Advice
Use HTML comments to organize sections in large HTML blocks.

The wording in the comment tag can be formatted any way you choose.

Syntax:
#+begin_src
<!-- SECTION:START -->
Some HTML
<!-- SECTION:END -->
#+end_src

Example:
#+html:<pre>#+begin_html<br>&lt;!-- SECTION:START --&gt;<br>Some HTML<br>&lt;!-- SECTION:END --&gt;<br><br>&lt;!-- OTHER_SECTION:START --&gt;<br>Some HTML<br>&lt;!-- OTHER_SECTION:END --&gt;<br>#+html_end</pre>

** Centering / Text Alignment
#+html:<p>The HTML attribute <code><a href="https://www.geeksforgeeks.org/html-align-attribute/">align</a></code> controls text alignment, including centering.</p>

Syntax:
#+begin_src
<element align="center">
Some stuff
</element>
#+end_src

Example:
#+html:<pre>#+html:&lt;div align="center"&gt;some centered stuff&lt;/div&gt;<br><br>or<br><br>#+begin_html<br>&lt;div align="center"&gt;<br>some centered stuff<br>&lt;/div&gt;<br>#+end_html</pre>
The centering attribute can be applied to many tags, but I recommend keeping it simple.

Recommended tags:
#+begin_example
<div> <-- Recommended over <p>, as it works more often.
<p>
#+end_example

Wrapping any other tags in these results in them being centered, regardless if they can accept the alignment attribute themselves.

Alignment options:
#+begin_example
left
right
center
justify
#+end_example

*** Centering Org Syntax
You can use HTML inline calls to start a center alignment and end it later.

Example:
#+html:<pre>#+html:&lt;div align="center"&gt;<br>* Org Heading<br>  Some text.<br>#+html:&lt;/div&gt;</pre>

Result:
#+html:<div align="center">
**** Org Heading
Some text.
#+html:</div>
*** Centering Org Tables
Centering org syntax includes the centering of org-tables.

Example:
#+html:<pre>#+html:&lt;div align="center"&gt;<br>| org | table |<br>| foo | bar  |<br>#+html:&lt;/div&gt;</pre>

Result:
#+html:<div align="center">
| org | table |
| foo | bar   |
#+html:</div>

*** Centering Code Blocks
It's also possible to center the text inside of a code block, not the block itself.

This is useful for posting ASCII art to your README.

Just use the div centering syntax on a code block. Either all in one or using starting the centering with an HTML inline call and closing it later, like in the previous example.

Syntax:
#+html:<pre>#+html:&lt;div align="center"&gt;<br>HTML or org code block<br>&lt;/div&gt;<br>&lt;/pre&gt;<br><br>or<br><br>#+html:&lt;div align="center"&gt;<br>#+begin_src<br>ASCII Art<br>#+end_src<br>#+html:&lt;/div&gt;</pre>

Example:
#+html:<div align="center">
#+begin_src
 /~~~\/~~\/~~~\/~~~\/~~\/~~~\                    /~~~\/~~\/~~~\/~~~\/~~\/~~~\
 | /\/ /\/ /\ || /\/ /\/ /\ |                    | /\ \/\ \/\ || /\ \/\ \/\ |
 \ \/ /\/ /\/ /\ \/ /\/ /\/ /                    \ \/\ \/\ \/ /\ \/\ \/\ \/ /
  \ \/\ \/\ \/  \ \/\ \/\ \/                      \/ /\/ /\/ /  \/ /\/ /\/ /
,_/\ \/\ \/\ \__/\ \/\ \/\ \______________________/ /\/ /\/ /\__/ /\/ /\/ /\_,
(__/\__/\__/\____/\__/\__/\________________________/\__/\__/\____/\__/\__/\__)
#+end_src
#+html:</div>

** Underlining
#+html:<p>Github honors the <code><a href="https://www.w3schools.com/TAGs/tag_ins.asp">insert</a></code> tag for underlining. Even though it's not specifically for underlining, it gets the job done.</p>

Syntax:
#+begin_src
<ins>
</ins>
#+end_src

Example:
#+html:<pre>#+html:&lt;ins&gt;some underlined text&lt;/ins&gt;<br><br>or<br><br>#+begin_html<br>&lt;ins&gt;<br>some underlined text<br>&lt;/ins&gt;<br>#+end_html</pre>
#+html:<caption>Result:</caption><br><ins>some underlined text</ins>
** Folding
This killer feature allows us to hide information in a fold. This is missing from org-mode, but fear not, HTML to the rescue.

#+html:<p>GitHub honors the <code><a href="https://www.w3schools.com/tags/tag_summary.asp">summary / details</a></code> tags for folding sections.</p>

Syntax:
#+begin_src
<details>
<summary>The title text or heading of our fold</summary>
<p>Some hidden text</p>
</details>
#+end_src

Example:
#+html:<pre>#+begin_html<br>&lt;details&gt;<br>&lt;summary&gt;Hidden Section - Click Me!&lt;summary&gt;<br>&lt;p&gt;Some hidden text&lt;/p&gt;<br>&lt;/details&gt;<br>#+end_html</pre>
*** Folding Org Syntax
You can use HTML inline calls to start a fold and end it later. Including folding regular org syntax.

#+html:<pre>#+html:&lt;details&gt;<br>#+html:&lt;summary&gt;&lt;b&gt;A Hidden Section - Click Me!&lt;/b&gt;&lt;/summary&gt;<br>* Org Heading<br>  Some text.<br>#+html:&lt;/details&gt;</pre>

Result:
#+html:<details>
#+html:<summary><b>A Hidden Section - Click Me!</b></summary>
**** Org Heading
Some text.
#+html:</details>
** Code
You can use both HTML and org-mode to generate code blocks. Each have their appropriate use cases.
*** Inline
=Looks like this.=

I use these to highlight commands and software where appropriate.
**** Org-mode

Syntax:
#+begin_src
Verbatim:
=SOME INFO= <-- My first choice.

or

Code:
~SOME INFO~ <-- Useful if text inside has an equal sign.
#+end_src

Advantages:
- Useful for quick inline highlighting.
- Text in these strings is not processed for org specific syntax.

Disadvantages:
#+begin_html
<ul>
<li>Does not always work on Github.</li>
<li>Cannot use org-mode link syntax to put a <code><a href="#org-syntax">link</a></code> inside of a code block.</li>
</ul>
#+end_html

**** HTML
#+html:<p>GitHub honors the <code><a href="https://www.w3schools.com/tags/tag_code.asp">code</a></code> tag for inline code blocks.</p>

Syntax:
#+begin_src
<code>some text</code>
#+end_src

Example:
#+html:<pre>#+html:&lt;code&gt;some text&lt;/code&gt;<br><br>or<br><br>#+begin_html<br>&lt;p&gt;This is an inline code with a &lt;code&gt;&lt;a href=""#html"&gt;link&lt;/a&gt;&lt;/code&gt;!&lt;/p&gt;<br>#+end_html</pre>

Result:
#+html:<p>This is an inline code block with a <code><a href="#html">link</a></code>!</p>

Advantages:
- More universal.
- Can include links and other formatting inside the code block.

Disadvantages:
- Not quick to use.

*** Block
#+html:<p>GitHub and org-ruby honor the <code><a href="https://www.w3schools.com/tags/tag_pre.asp">pre</a></code> tag for code blocks.</p>

Org syntax is translated through org-ruby to the pre tag. Here, org and HTML are very equivalent, except for one disadvantage shown below.

**** Org-mode
Syntax:
#+begin_src
,#+begin_src
,#+end_src

or

,#+begin_example
,#+end_example

#+end_src

Example:
#+begin_src
,#+begin_src
Some code
More code
,#+end_src
#+end_src

Result:
#+begin_src
Some code
More code
#+end_src

Advantages:
- Quick to write.
- Can write any language, including org-mode syntax. Just prepend an org command with a comma.

Disadvantages:
- Cannot include org-mode links inside inside.

**** HTML
Syntax:
#+begin_src
<pre>some HTML</pre>
#+end_src

Example:
#+html:<pre>#+html:&lt;pre&gt;Some code or org-syntax: #+begin_src&lt;/pre&gt;<br><br>or<br><br>#+begin_html<br>&lt;pre&gt;<br>Some code<br>&lt;/pre&gt;<br>#+end_html</pre>

Advantages:
- The inline HTML org syntax can use org syntax in the code block.

Disadvantages:
- Not easy to use.
- To Write HTML inside an HTML code block, you must replace the tag brackets (< >) with &lt; and &gt; (&lt;tag element&gt;).
** Tables
Org-ruby translates org tables to HTML just fine, but has some shortcomings.

For regular tables, this is the faster and simpler approach.

If your only table customization goal is to center it, refer to [[#centering-org-tables][centering org tables]] above!

For more advanced formatting you may want an HTML table, which allows you to take advantage of aligning and other formatting.

Unfortunately, GitHub does not honor Org's table alignment syntax when exporting it through org-ruby.
*** HTML Tables From Org Tables.
Generate your table using org-mode, since it's quick and easy compared to writing an HTML table, and then export the table using the following technique.

1. Create your org table.
2. Use the command: org-html-export-as-html to export the current org document buffer to an HTML buffer.
3. Copy the HTML table into an HTML block in your org document, replacing the org table.
4. Apply any additional HTML formatting to your table.

** Shields
Shields are the little badges found on repositories all over GitHub to quickly and visually share information about the repository to the reader.

The only way to put shields in an org document is through HTML.

Here is the most used website to generate shields: [[https://shields.io/][shields.io]]

Just use the URL generated as the source for an image tag.

Syntax:
#+begin_src
Without link:
<img src="https://img.shields.io/badge/Org-Document-%2377aa99?style=flat-square&logo=org&logoColor=white">

With link:
<a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-Document-%2377aa99?style=flat-square&logo=org&logoColor=white"></a>
#+end_src

Example:
#+html:<pre>#+html:&lt;a href="https://orgmode.org"&gt;&lt;img src="https://img.shields.io/badge/Org-Document-%2377aa99?style=flat-square&logo=org&logoColor=white"&gt;&lt;/a&gt;</pre>

Result:
#+html:<a href="https://orgmode.org"><img src="https://img.shields.io/badge/org-document-%2377aa99?style=flat-square&logo=org&logocolor=white"></a>

Tip:
I like to center my shields by enclosing it in a paragraph tag with an alignment attribute.

** Emojis
The only way to use emojis an org document on GitHub is through HTML.

1. Find the GitHub emoji you want to use.
2. Use the syntax :emoji_name: anywhere in a text field and the emoji will show up!

Example:
#+html:<pre>#+html:&lt;p&gt;Here is an emoji: :satisfied:&lt;/p&gt;</pre>

Result:
#+html:<p>Here is an emoji: :satisfied:</p>
