#+HTML:<h1 align="center">GitHub README.org Hacks</h1>
#+HTML: <p align="center"><a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-Document-%2377aa99?style=flat-square&logo=org&logoColor=white"> </a><a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Made_with-Emacs-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a></p>

#+HTML:<div align="center">
Sharing the undocumented things you can do with GitHub, org-mode, and HTML to make a better README.
#+HTML:</div>
** Why?
The README, is your primary method to portray information about a repository to the reader. GitHub supports using =org-mode= to create a README, but it's implementation using =org-ruby= neither works as claimed nor is complete.

That's where these hacks come in, primarily using HTML, to get around these limitations, as well as to show some additional possibilities and preferences.

** Document Structure
This document covers methods to use org-mode and HTML together. The headings are sorted by the goal we want to achieve, not by the method used to achieve it.

** Table of Contents
- [[#background][Background]]

** Background
GitHub uses [[https://github.com/wallyqs/org-ruby][org-ruby]] to parse and export an org document as HTML, then it is sanitized using their [[https://github.com/gjtorikian/html-pipeline/blob/main/lib/html/pipeline/sanitization_filter.rb][HTML-pipeline]].

These documents allow us to understand what you can and can't do using org-mode and HTML on GitHub, but that work is summarized for you here.
*** org-ruby
Through this, org-mode syntax is translated directly into HTML. The rules for translation are modifiable. See org-ruby for the default translation list.

The problem with this, is that the translations used by GitHub/org-ruby are incomplete. This can be fixed by including a YAML file, but we don't need another file in our repository just for formatting a README.

The point is, that most things you can do with org-mode are supported, but some things are not. For example, headings are translated directly to HTML heading tags (<h1>,<h2>,etc.), tables are translated to table tags (<table>), etc.

_However, the following do not work correctly and must be fixed using HTML:_
**** Centering
#+HTML:<p>Org-mode's <code>#+BEGIN_CENTER</code> and <code>#+END_CENTER</code> syntax are translated to <code>&lt;div&gt;</code> but it's missing the <code>align="center"</code> attribute.

**** Underlining
Org-mode's underline syntax =_text_= is translated to ~<span style=\"text-decoration:underline;\>~ which is incorrect and not honored by GitHub.

**** Folding
In general this is missing from org-mode, a feature that markdown has and "we" don't.

**** Verses
Org-mode's =#+BEGIN_VERSE= and =#+END_VERSE= syntax has no translation to HTML. This is not a problem for us, since rarely do we have verses in a /code/ repository.
